name: Issue assignment

on:
    issues:
        types: [opened,edited]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
          - name: Check if issue has [Proposal] label
            id: check_proposal_label
            run: |
                echo "has_proposal_label=${{ contains(github.event.issue.title, 'proposal') }}" >> "$GITHUB_OUTPUT"
            shell: bash

          - name: Run auto-assignment script
            id: check_proposal_label_1
            if: ${{steps.check_proposal_label.outputs.has_proposal_label == 'true'}}
            run: |
                category3=$(echo "${{ github.event.issue.body }}" | grep -e "Category" -A2 | grep -v "Category" | grep "\S" | tr -d " \t\n\r" | tr -d '"')
                echo "category=$category3" >> "$GITHUB_OUTPUT"
            shell: bash

          - name: 'Auto-assign issue1'
            if: ${{steps.check_proposal_label_1.outputs.category == 'SDKs' || 'Specification'}}
            uses: pozil/auto-assign-issue@v1
            with:
                assignees: mihirm21
                numOfAssignee: 0
                allowSelfAssign: true
          
          # - name: 'Auto-assign issue2'
          #   if: ${{steps.check_proposal_label_1.outputs.category == 'Flagd' || 'OpenFeatureOperator'}}
          #   uses: pozil/auto-assign-issue@v1
          #   with:
          #       assignees: mihirm21
          #       # numOfAssignee: 2
          #       allowSelfAssign: true
          

